package com.xpanxion.report;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import com.xpanxion.model.Customer;
import com.xpanxion.model.Fees;
import com.xpanxion.service.CustomerService;
import com.xpanxion.service.FeesService;

/*import com.xpanxion.gym.model.Employee;
import com.xpanxion.gym.service.EmployeeService;*/

/**
 * A Spring controller that allows the users to download a PDF document
 * generated by the iText library.
 * 
 * @author www.codejava.net
 * 
 */
@Controller
public class MainController {

	@Autowired
	private FeesService feesService;
	
	@Autowired
	private CustomerService customerService;
	
	@RequestMapping(value = "/downloadPDF", method = RequestMethod.POST)
	public ModelAndView downloadExcel(String month) {
		System.out.println(month);
		// create some sample data66
		System.out.println("*************************************");
		/*List<Fees> listBooks1 = employeeService.listEmployee();
 		 return a view which will be resolved by an excel view resolver
 
		return new ModelAndView("pdfView", "listBooks", listBooks1);*/
		
		List<Fees> listfees=feesService.listMonthlyFees(month);
		ModelAndView m= new ModelAndView();
		List<Customer> listcust = customerService.listCustomer();
		m.addObject("customers",listcust );
		m.setViewName("pdfView");
		m.addObject("listFees", listfees);
		//return new ModelAndView("pdfView", "listFees", listfees);
		return m;
	}
}
